#include "led.h"
#include "sam.h"
#include "same51j20a.h"

void clkLED(){
    GCLK_REGS->GCLK_GENCTRL[3] = GCLK_GENCTRL_DIV(60) | GCLK_GENCTRL_SRC_DFLL | GCLK_GENCTRL_GENEN_Msk;

    GCLK_REGS->GCLK_PCHCTRL[TCC2_GCLK_ID] = GCLK_PCHCTRL_GEN_GCLK3 | GCLK_PCHCTRL_CHEN_Msk;
    while((GCLK_REGS->GCLK_PCHCTRL[TCC2_GCLK_ID] & GCLK_PCHCTRL_CHEN_Msk) != GCLK_PCHCTRL_CHEN_Msk){

        //WAIT FOR SYNCS
    }//while

    MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_TCC2_Msk;
}

void portLED(){


    PORT_REGS->GROUP[0].PORT_PINCFG[16] |= PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PMUX[8] |= PORT_PMUX_PMUXE_F;
 


}