#include "led.h"
#include "same51j20a.h"

// USES TC0 which has pad PA04 for pwm
void clkLED(){
    GCLK_REGS->GCLK_GENCTRL[3] = GCLK_GENCTRL_DIV(60) | GCLK_GENCTRL_SRC_DFLL | GCLK_GENCTRL_GENEN_Msk;
  while((GCLK_REGS->GCLK_SYNCBUSY & GCLK_SYNCBUSY_GENCTRL_GCLK3) == GCLK_SYNCBUSY_GENCTRL_GCLK3)

    GCLK_REGS->GCLK_PCHCTRL[TC0_GCLK_ID] = GCLK_PCHCTRL_GEN_GCLK3 | GCLK_PCHCTRL_CHEN_Msk;
    while((GCLK_REGS->GCLK_PCHCTRL[TC0_GCLK_ID] & GCLK_PCHCTRL_CHEN_Msk) != GCLK_PCHCTRL_CHEN_Msk){

        //WAIT FOR SYNCS
    }//while

    MCLK_REGS->MCLK_APBCMASK |= MCLK_APBAMASK_TC0_Msk;
}

void portLED(){

PORT_REGS->GROUP[0].PORT_DIRSET = PORT_PA04;
PORT_REGS->GROUP[0].PORT_OUTSET = PORT_PA04;
PORT_REGS->GROUP[0].PORT_PINCFG[4] |= PORT_PINCFG_PMUXEN_Msk;
PORT_REGS->GROUP[0].PORT_PMUX[2] |= PORT_PMUX_PMUXE_E;

}

void initLED(){
    TC0_REGS->COUNT8.TC_CTRLA = TC_CTRLA_MODE_COUNT8;
    TC0_REGS->COUNT8.TC_WAVE =  TC_WAVE_WAVEGEN_NPWM;

}

void startLED(){
    initLED();
    TC0_REGS->COUNT8.TC_CTRLA |= TC_CTRLA_ENABLE_Msk;
}

void updateOutput(uint8_t dutyCycle)
{
  TC0_REGS->COUNT8.TC_CC[1] = dutyCycle;
}